spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3307/delivery_db
    password: adm123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'

